# Generated by Django 3.2.5 on 2021-08-28 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=80)),
                ('poza', models.ImageField(blank=True, default='pictures/none.png', null=True, upload_to='pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Produse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=80)),
                ('nume_latin', models.CharField(max_length=80)),
                ('poza', models.ImageField(blank=True, default='pictures/none.png', null=True, upload_to='pictures/')),
                ('specie', models.CharField(max_length=80)),
                ('familie', models.CharField(max_length=80)),
                ('descriere', models.TextField()),
                ('pret', models.PositiveIntegerField(default=0)),
                ('stoc', models.PositiveIntegerField(default=0)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produse.categorii')),
            ],
        ),
        migrations.CreateModel(
            name='Promotii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pret_redus', models.PositiveIntegerField(default=0)),
                ('procent', models.BooleanField(default=False)),
                ('data_inceput', models.DateField(auto_now=True)),
                ('durata', models.PositiveIntegerField(default=1)),
                ('produse_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produse.produse')),
            ],
        ),
        migrations.CreateModel(
            name='Poze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poza', models.ImageField(blank=True, default='pictures/none.png', null=True, upload_to='pictures/')),
                ('produse_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produse.produse')),
            ],
        ),
    ]
