# Generated by Django 3.2.5 on 2021-08-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produse', '0003_auto_20210828_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotii',
            name='produse_id',
        ),
        migrations.AddField(
            model_name='promotii',
            name='produse_id',
            field=models.ManyToManyField(blank=True, to='produse.Produse'),
        ),
    ]
