# Generated by Django 3.2.5 on 2021-09-04 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produse', '0004_auto_20210829_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotii',
            name='durata',
        ),
        migrations.AddField(
            model_name='promotii',
            name='data_sfarsit',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='promotii',
            name='data_inceput',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
