# Generated by Django 3.2.5 on 2021-09-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produse', '0006_useri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useri',
            name='det_adresa',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='useri',
            name='nr_strada',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
