# Generated by Django 3.2.5 on 2021-09-23 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produse', '0007_auto_20210921_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.PositiveIntegerField(default=1)),
                ('pret_unitar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produs_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produse.produse')),
            ],
            options={
                'verbose_name': 'Item comanda',
                'verbose_name_plural': 'Itemi comanda',
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referinta', models.CharField(max_length=80)),
                ('tip_plata', models.CharField(choices=[('NUM', 'Numerar, la livrare'), ('CRD', 'Cu cardul'), ('TRB', 'Transfer bancar')], max_length=3)),
                ('platita', models.BooleanField(default=False)),
                ('data_plata', models.DateField(blank=True)),
                ('livrata', models.BooleanField(default=False)),
                ('data_livrare', models.DateField(blank=True)),
                ('itemi', models.ManyToManyField(blank=True, to='produse.ItemComanda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produse.useri')),
            ],
            options={
                'verbose_name': 'Comandă',
                'verbose_name_plural': 'Comenzi',
            },
        ),
    ]
