# Generated by Django 3.2.5 on 2021-09-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produse', '0008_comanda_itemcomanda'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comanda',
            new_name='Comenzi',
        ),
    ]
