# Generated by Django 3.2.5 on 2021-09-24 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produse', '0010_auto_20210924_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='comenzi',
            name='data_creare',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
